[package]
name = "scarefire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glam = "0.25.0"
glfw = "0.54.0"
glrs = "0.1.0"
paste = "1.0.14"
stb_image = "0.3.0"
weak-table = "0.3.2"
